### ISSUE TITLE
Could the document hint be wider?

### ISSUE THREAD

**Issue by foreshadow** [autocomplete-python/autocomplete-python#335]
Hi,
I got a function with very long document.
And when I complete the function name, it shows a thin and long autocomplete dropdown.
Sometimes it goes beyond my screen.
It seems that the width depends on the maximum width of the candidates.
Would it be possible that we have auto adjustment of width when it is too long?
Besides, can we configure its font (to monospace for example)? As we may have alignment in the document.

Thanks.
Infinity

![image](https://user-images.githubusercontent.com/2712675/29874811-7376cf1e-8dca-11e7-9104-82b24c369651.png)

**Comment by sadovnychyi** [comment]
I think this is something that should be configurable from autocomplete-plus package, but you can override it in your local styles.less file with something like:

```css
atom-text-editor[data-grammar="source python"], :host {
  .autocomplete-suggestion-list.select-list.popover-list .suggestion-description {
    max-height: 30em;
    overflow: auto;
  }
}
```
