### ISSUE TITLE
Configuration using python that runs on docker hosting linux

### ISSUE THREAD

**Issue by Locustv2** [autocomplete-python/autocomplete-python#408]
I have a host machine running Mac OS. I use atom as my editor. However my development environment is dockerized on an ubuntu machine. My docker machine runs python 3.6 and i access it on my host through `docker -i --user 1000:1000 docker_machine python3`. That means i have an executable at `/usr/local/bin/python`.

I mount my whole user directory to the user directory in the docker machine.

Inside the docker machine, all my python projects use virtual environments through `pipenv`.

my config for autocomplete-python is:

```json
"*":
  "autocomplete-python":
    extraPaths: "$PROJECT/.venv/lib/python3.6/site-packages"
    pythonPaths: "/usr/local/bin/python"
    useKite: false
```

This is the current config that i am running. But it's not the correct config since the `python` binary is not the one from the virtual environment. If i point it to the one in the venv using `$PROJECT/.venv/bin/python` i get an error saying that `....... .venv/bin/python: cannot execute binary file` which is obvious since it's a linux binary and not a mac one.

The correct way to execute it would be though docker using:

`docker -i --user 1000:1000 docker_machine /path/to/project/venv/bin/python`.

I have tried to put this in my config but it does not works.

Are there any way of using the venv python?

**Comment by cagriar** [comment]
Hi @Locustv2 have you managed to solve this problem?

**Comment by Locustv2** [comment]
@cagriar  no but my alternative is to create another executable. So i create `dude` xD


docker-compose.yml
```yaml
version: '3'
services:
    dude:
        build:
            context: .
            dockerfile: Dockerfile
        dns:
            - 8.8.8.8
        volumes:
            - ${HOME}:${HOME}:delegated
        working_dir: ${HOME}
        network_mode: "host"
        environment:
            HOME: ${HOME}
            USER: ${USER}
            LC_ALL: C.UTF-8
            LANG: C.UTF-8
            PIPENV_VENV_IN_PROJECT: "true"
```

Dockerfile
```
FROM python:3.6

RUN apt-get update
RUN apt-get install -y apt-utils
RUN apt-get install -y software-properties-common nano sudo iputils-ping less groff git ruby ruby-dev bash-completion netcat wget jq

RUN pip install pipenv
RUN pip install ipython
RUN pip install 'python-language-server[all]'
```

/usr/local/bin/dude
```
#!/bin/bash
docker-compose -f ~/trivago/docker-compose.yml run --rm -w ${PWD} dude "$@
```

normally when i would execute a python script, i would do:
```
python some/dir/some/script.py
```
And with that, everytime i want to execute a python thing, i just add dude at the beginning...

```
dude python some/dir/some/script.py
```

It feels like talking to your pc...
and if you want to do something that's not working you can still go into the docker container and execute there:

```
dude bash
python some/dir/some/script.py
```
